export const fontSizes = [
    { value: '8px', },
    { value: '9px', },
    { value: '10px', },
    { value: '11px', },
    { value: '12px', },
    { value: '14px', },
    { value: '16px', },
    { value: '18px', },
    { value: '20px', },
    { value: '22px', },
    { value: '24px', },
    { value: '26px', },
    { value: '28px', },
    { value: '36px', },
    { value: '48px', },
    { value: '72px', },
]