INSERT INTO PARAMETER (ID, TABLE_NAME, ORDER_PARAMETER, VALUE_REGISTRY) VALUES (1, '00', 0, 'false') ON CONFLICT DO NOTHING;
INSERT INTO VOCABULARY (ID, HAS_NEW_WORDS, WHEN_UPDATED) VALUES (1, false, null) ON CONFLICT DO NOTHING;
